/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.falhad

import kotlinx.coroutines.runBlocking
import kotlin.test.Test

class ZarinpalTest {
    @Test
    fun createPayment() {
        val zarinpal = Zarinpal("XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-X")
        runBlocking {

            println("running..")
            val createPayment = zarinpal.createPayment(
                amount = 1000,
                description = "description",
                callbackURL = "http://localhost:8080/verify",
                email = "cs.arcxx@gmail.com",
                mobile = "9307540810"
            )
            println("finished..")
            println(createPayment.message)
            println(createPayment.data)
            println(createPayment.exception)
//            when (createPayment) {
//                is Zarinpal.ApiResult.Error -> {
//                    println("error: ${createPayment.message}")
//                }
//
//                is Zarinpal.ApiResult.Success -> {
//                    val webGatewayUrl = createPayment.data?.webGatewayUrl()
//                    println("navigate to $webGatewayUrl")
//                }
//            }
        }
    }
}
