/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.falhad

import kotlinx.coroutines.*
import kotlin.test.Test
import kotlin.test.assertTrue

class ZarinpalTest {
    @Test fun createPayment() {
        val zarinpal = Zarinpal("XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-X", sandbox = true)
        runBlocking {

            println("running..")
            val createPayment = zarinpal.createPayment(
                amount = 100,
                description = "description",
                callbackURL = "http://localhost:8080/verify",
                email = "cs.arcxx@gmail.com",
                mobile = "9307540810"
            )
            println("finished..")
            when(createPayment){
                is ApiResult.Error ->{
                    println("error: ${createPayment.message}")
                }
                is ApiResult.Success -> {
                    val webGatewayUrl = createPayment.data?.webGatewayUrl()
                    println("navigate to $webGatewayUrl")
                }
            }
        }
    }
}
